# Generated by Django 5.1.6 on 2025-02-19 09:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('police', 'Police'), ('investigator', 'Investigator'), ('judge', 'Judge')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date_reported', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('evidence_files', models.FileField(blank=True, upload_to='evidence/')),
                ('timeline', models.JSONField(blank=True, default=dict)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.crime')),
                ('investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='JudicialCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heard', models.DateField()),
                ('court_location', models.CharField(max_length=255)),
                ('verdict', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('hearing_dates', models.JSONField(blank=True, default=dict)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.crime')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiling.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Offender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('social_media_links', models.JSONField(blank=True, default=dict)),
                ('criminal_record', models.TextField(blank=True)),
                ('crimes_committed', models.ManyToManyField(related_name='offenders', to='profiling.crime')),
            ],
        ),
    ]
