# Generated by Django 5.1.6 on 2025-03-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='documents',
            field=models.FileField(default=5, upload_to=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Offender',
        ),
    ]
