# Generated by Django 5.1.6 on 2025-03-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judicialcase',
            name='hearing_dates',
        ),
        migrations.AddField(
            model_name='judicialcase',
            name='hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
