# Generated by Django 5.1.6 on 2025-03-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiling', '0002_remove_judicialcase_hearing_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='timeline',
        ),
    ]
